### ISSUE TITLE
crash on latest pkhex 

### ISSUE THREAD

**Issue by Anatros-lafisques** [projectpokemon/EventsGallery#442]
so i went to update to the latest pkhex today ver: 24.06.03 and now the plugin seems to be causing a error and crashes the program. this is the error log im getting from pkhex looks like something has changed in the last few updates that breaks the plugin

System.MethodAccessException: Attempt by method 'WC3Plugin.LocalizationUtil.GetStringList(System.String)' to access method 'PKHeX.Core.Util.LoadStringList(System.String, System.String)' failed.
   at WC3Plugin.LocalizationUtil.GetStringList(String fileName)
   at WC3Plugin.LocalizationUtil.SetLocalization(String currentCultureCode)
   at WC3Plugin.WC3Plugin.Initialize(Object[] args)
   at PKHeX.WinForms.Main.FormLoadPlugins()
   at PKHeX.WinForms.Main..ctor()
   at PKHeX.WinForms.Program.Main()
System.InvalidOperationException: Invoke or BeginInvoke cannot be called on a control until the window handle has been created.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Action method)
   at PKHeX.WinForms.ErrorWindow.ShowErrorDialog(String friendlyMessage, Exception ex, Boolean allowContinue)
   at PKHeX.WinForms.Program.CurrentDomain_UnhandledException(Object sender, UnhandledExceptionEventArgs e)

**Comment by kamronbatman** [comment]
Sorry for the confusion, this is is the events gallery, not PKHex github repositoriy.

Please make an issue ticket here: https://github.com/kwsch/PKHeX
